public enum Tags {
  SUPERNODO_REQUEST_RECURSOS,
  SUPERNODO_REQUEST_RECURSO,
  REGISTRA_NOVO_NODO,
  NODO_REQUEST_RECURSOS,
  NODO_RESPONSE_RECURSOS,
  NODO_REQUEST_RECURSO,
  NODO_RESPONSE_RECURSO,
  P2P_REQUEST,
  P2P_RESPONSE,
  ALIVE
}
