all:			Client.class Server.class \
			ServerInterface.class SemaphoreServer.class SemaphoreServerInterface.class

Client.class:		Client.java
			@javac Client.java

Server.class:		Server.java
			@javac Server.java

ServerInterface.class:	ServerInterface.java
			@javac ServerInterface.java

SemaphoreServer.class: SemaphoreServer.java
			@javac SemaphoreServer.java

SemaphoreServerInterface.class: SemaphoreServerInterface.java
			@javac SemaphoreServerInterface.java

